<?php
/**
 * Created by PhpStorm.
 * User: ehsani
 * Date: 1/10/19
 * Time: 2:52 PM
 */
namespace Api;

class ErrorList
{
    /**
     * each error contains ErrorCode and ErrorMessage

    const BAD_QUERY_PARAMETER = array( "code" => "BAD_QUERY_PARAMETER" , "message" => "");
    const NOT_FOUND = array( "code" => "NOT_FOUND" , "message" => "");
    const PROBLEM_IN_ADDING_STUDENT_WORK_PRICE = array( "code" => "PROBLEM_IN_ADDING_STUDENT_WORK_PRICE" , "message" => "");
    const PROBLEM_IN_UPDATING_STUDENT_WORK_PRICE = array( "code" => "PROBLEM_IN_UPADTING_STUDENT_WORK_PRICE" , "message" => "");
    const PROBLEM_IN_DELETING_STUDENT_WORK_PRICE = array( "code" => "PROBLEM_IN_DELETING_STUDENT_WORK_PRICE" , "message" => "");
     * */

    const PERSON_ID_IS_MISSING = array( "code" => "PERSON_ID_IS_MISSING_IN_HEADER" , "message" => "PERSON_ID_IS_MISSING_IN_HEADER");
    const IP_ADDRESS_IS_MISSING = array( "code" => "IP_ADDRESS_IS_MISSING_IN_HEADER" , "message" => "IP_ADDRESS_IS_MISSING_IN_HEADER");
    const SYS_KEY_IS_MISSING = array( "code" => "SYS_KEY_IS_MISSING_IN_HEADER" , "message" => "SYS_KEY_IS_MISSING_IN_HEADER");
    const USER_ROLE_IS_MISSING = array( "code" => "USER_ROLE_IS_MISSING_IN_HEADER" , "message" => "USER_ROLE_IS_MISSING_IN_HEADER");
    const USER_ID_IS_MISSING = array( "code" => "USER_ID_IS_MISSING_IN_HEADER" , "message" => "USER_ID_IS_MISSING_IN_HEADER");
    const H_TOKEN_IS_MISSING = array( "code" => "H_TOKEN_IS_MISSING_IN_HEADER" , "message" => "H_TOKEN_IS_MISSING_IN_HEADER");

    const API_KEY_IS_MISSING = array( "code" => "API_KEY_IS_MISSING_IN_HEADER" , "message" => "API_KEY_IS_MISSING_IN_HEADER");


    const INVALID_QUERY_PARAMETER= array("code"=>"INVALID_QUERY_PARAMETER", "message"=>"INVALID_QUERY_PARAMETER");
    const INPUT_VALIDATION_FAILED= array("code"=>"INPUT_VALIDATION_FAILED", "message"=>"INPUT_VALIDATION_FAILED");
    const REQUEST_ID_IS_NOT_VALID =array("code"=>"REQUEST_ID_IS_NOT_VALID", "message"=>"REQUEST_ID_IS_NOT_VALID");
    const INVALID_TOKEN = array("code"=>"INVALID_H_TOKEN", "message"=>"INVALID_H_TOKEN");
    const UNSUPPORTED_FILE_TYPE = array("code"=>"UNSUPPORTED_FILE_TYPE", "message"=>"UNSUPPORTED_FILE_TYPE");
    const CLASS_IS_FULL= array("code"=>"CLASS_IS_FULL", "message"=>"CLASS_IS_FULL");
    const INVALID_API_KEY = array("code"=>"INVALID_API_KEY", "message"=>"INVALID_API_KEY");
    const CLASS_IS_EXSIST_FOR_YOU = array("code"=>"CLASS_IS_EXSIST_FOR_YOU", "message"=>"CLASS_IS_EXSIST_FOR_YOU");
    const REQUEST_ID_IS_REQUIRED = array("code"=>"REQUEST_ID_IS_REQUIRED", "message"=>"REQUEST_ID_IS_REQUIRED");

    const INPUT_VALIDATION_FAILED_FOR_PERSON_ID= array("code"=>"INPUT_VALIDATION_FAILED_FOR_PERSON_ID", "message"=>"INPUT_VALIDATION_FAILED_FOR_PERSON_ID");
    const INPUT_VALIDATION_FAILED_FOR_USER_ROLES= array("code"=>"INPUT_VALIDATION_FAILED_FOR_USER_ROLES", "message"=>"INPUT_VALIDATION_FAILED_FOR_USER_ROLES");
    const INPUT_VALIDATION_FAILED_FOR_SYS_KEY= array("code"=>"INPUT_VALIDATION_FAILED_FOR_SYS_KEY", "message"=>"INPUT_VALIDATION_FAILED_FOR_SYS_KEY");
    const INPUT_VALIDATION_FAILED_FOR_IP_ADDRESS= array("code"=>"INPUT_VALIDATION_FAILED_FOR_IP_ADDRESS", "message"=>"INPUT_VALIDATION_FAILED_FOR_IP_ADDRESS");


    const INPUT_VALIDATION_FAILED_FOR_API_KE= array("code"=>"INPUT_VALIDATION_FAILED_FOR_API_KEY", "message"=>"INPUT_VALIDATION_FAILED_FOR_API_KEY");


    const INPUT_VALIDATION_FAILED_FOR_NID= array("code"=>"INPUT_VALIDATION_FAILED_FOR_NID", "message"=>"INPUT_VALIDATION_FAILED_FOR_NID");
    const INPUT_VALIDATION_FAILED_FOR_FNAME= array("code"=>"INPUT_VALIDATION_FAILED_FOR_FNAME", "message"=>"INPUT_VALIDATION_FAILED_FOR_FNAME");
    const INPUT_VALIDATION_FAILED_FOR_LNAME= array("code"=>"INPUT_VALIDATION_FAILED_FOR_LNAME", "message"=>"INPUT_VALIDATION_FAILED_FOR_LNAME");
    const INPUT_VALIDATION_FAILED_FOR_GENDER= array("code"=>"INPUT_VALIDATION_FAILED_FOR_GENDER", "message"=>"INPUT_VALIDATION_FAILED_FOR_GENDER");
    const INPUT_VALIDATION_FAILED_FOR_PHONE= array("code"=>"INPUT_VALIDATION_FAILED_FOR_PHONE", "message"=>"INPUT_VALIDATION_FAILED_FOR_PHONE");
    const INPUT_VALIDATION_FAILED_FOR_FATHERNAME= array("code"=>"INPUT_VALIDATION_FAILED_FOR_FATHERNAME", "message"=>"INPUT_VALIDATION_FAILED_FOR_FATHERNAME");
    const INPUT_VALIDATION_FAILED_FOR_ADDRESS= array("code"=>"INPUT_VALIDATION_FAILED_FOR_ADDRESS", "message"=>"INPUT_VALIDATION_FAILED_FOR_ADDRESS");
    const INPUT_VALIDATION_FAILED_FOR_ACCOUNTNO= array("code"=>"INPUT_VALIDATION_FAILED_FOR_ACCOUNTNO", "message"=>"INPUT_VALIDATION_FAILED_FOR_ACCOUNTNO");
    const INPUT_VALIDATION_FAILED_FOR_BIRTDATE= array("code"=>"INPUT_VALIDATION_FAILED_FOR_BIRTDATE", "message"=>"INPUT_VALIDATION_FAILED_FOR_BIRTDATE");



    //const


}